### ISSUE TITLE
Add a function to detect if the system runs a dual pam stack (64 and 32 bits)

### ISSUE THREAD

**Issue by scabrero** [yast/yast-pam#27]
Some YaST modules like yast-auth-client or yast-samba-client adjust the PAM configuration adding or removing PAM modules.

If the system has a dual PAM stack installed (pam-32bit), then these modules will fail if the 32bit version of the PAM module being added or removed isn't installed, e.g. [bug](https://bugzilla.suse.com/show_bug.cgi?id=1190873)

The YaST PAM module should provide a function to check if the system runs a dual PAM stack so each YaST module can add to the list of packages to install the packages providing the 32bit version of the PAM modules when necessary (e.g. samba-winbind-32bit or sssd-32bit).

Just for reference, pam-config implementation of this check: https://github.com/SUSE/pam-config/blob/v1.1/src/sanity_checks.c#L31

**Comment by kobliha** [comment]
I don't think that this is handled by PAM at all, IMO it's samba-client.

**Comment by scabrero** [comment]
> I don't think that this is handled by PAM at all, IMO it's samba-client.

pam-config, invoked by yast-pam, handles it.

yast-auth-client also adds pam_sss, I would prefer to avoid adding duplicated code to all YaST modules adding or removing PAM modules.
